# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  encoding: unicode
  database: ticket_app
  pool: 19
  username: spendar89
  password:
  allow_concurrency: true
  
production:
  adapter: postgresql
  encoding: unicode
  database: ticket_app
  pool: 19
  username: spendar89
  password:
  allow_concurrency: true

test:
  adapter: postgresql
  encoding: unicode
  database: ticket_app
  pool: 19
  username: spendar89
  password:
  allow_concurrency: true
